name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set tag
      run: export TAG=$(date +%s)    
    - name: Build image
      run: docker build . --file Dockerfile --tag rayh/eks-deployer:$TAG
    - name: Push image
      run: |
        docker push rayh/eks-deployer:$TAG
        docker tag rayh/eks-deployer:$TAG rayh/eks-deployer:latest
        docker push rayh/eks-deployer:latest
